using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections.Generic;

#region MenuEntry
public class PrefabContextMenu
{
    [MenuItem("Assets/Kira工具/MVVM/为UI预制体生成View脚本", true)]
    private static bool Validate()
    {
        var obj = Selection.activeObject;
        return obj != null && PrefabUtility.IsPartOfPrefabAsset(obj);
    }

    [MenuItem("Assets/Kira工具/MVVM/为UI预制体生成View脚本")]
    private static void Generate()
    {
        var prefab = Selection.activeObject as GameObject;
        if (prefab == null) return;

        string defaultPath = $"Assets/Scripts/Generated/GeneratedUI/{prefab.name}.cs";
        if (File.Exists(defaultPath))
        {
            PrefabScriptGenerator.UpdateExistingScript(prefab, defaultPath);
        }
        else
        {
            PrefabScriptGeneratorWindow.OpenWindow(prefab, defaultPath);
        }
    }
}
#endregion


#region GeneratorWindow
public class PrefabScriptGeneratorWindow : EditorWindow
{
    private GameObject prefab;
    private string scriptPath;
    private string authorName = "Kira";

    public static void OpenWindow(GameObject prefab, string defaultPath)
    {
        var window = CreateInstance<PrefabScriptGeneratorWindow>();
        window.prefab = prefab;
        window.scriptPath = defaultPath;
        window.titleContent = new GUIContent("生成 UI 脚本");
        window.ShowUtility();
    }

    private void OnGUI()
    {
        if (prefab == null)
        {
            EditorGUILayout.HelpBox("Prefab 丢失。", MessageType.Error);
            return;
        }

        EditorGUILayout.LabelField("预制体：", prefab.name);
        scriptPath = EditorGUILayout.TextField("脚本路径：", scriptPath);
        authorName = EditorGUILayout.TextField("创建者：", authorName);

        GUILayout.Space(10);
        if (GUILayout.Button("生成脚本"))
        {
            PrefabScriptGenerator.GenerateNewScript(prefab, scriptPath, authorName);
            Close();
        }
    }
}
#endregion


#region GeneratorCore
public static class PrefabScriptGenerator
{
    public static void GenerateNewScript(GameObject prefab, string scriptPath, string author)
    {
        Debug.Log($"[PrefabScriptGenerator] 开始生成脚本：{scriptPath}");

        var dir = Path.GetDirectoryName(scriptPath);
        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
            Debug.Log($"[PrefabScriptGenerator] 创建目录：{dir}");
        }

        var info = CollectUIInfo(prefab);
        string generatedCode = BuildGeneratedRegion(info);
        string finalCode = BuildFullClass(prefab, author, generatedCode, info.usings);

        File.WriteAllText(scriptPath, finalCode, Encoding.UTF8);
        AssetDatabase.Refresh();
        Debug.Log($"[PrefabScriptGenerator] 脚本生成完成，等待 Unity 编译：{scriptPath}");

        DeferredBinder.ScheduleBinding(prefab, scriptPath, info);
        Debug.Log($" 已为 {prefab.name} 生成脚本，等待编译后自动绑定引用。");
    }

    public static void UpdateExistingScript(GameObject prefab, string scriptPath)
    {
        Debug.Log($"[PrefabScriptGenerator] 检测到脚本存在，开始更新：{scriptPath}");

        var info = CollectUIInfo(prefab);
        string newGeneratedCode = BuildGeneratedRegion(info);
        string existing = File.ReadAllText(scriptPath, Encoding.UTF8);
        string finalCode = ReplaceRegion(existing, "AutoGenerated", newGeneratedCode);
        finalCode = MergeUsings(finalCode, info.usings);

        File.WriteAllText(scriptPath, finalCode, Encoding.UTF8);
        AssetDatabase.Refresh();
        Debug.Log($"[PrefabScriptGenerator] 已更新 AutoGenerated 区域，等待 Unity 编译：{scriptPath}");

        DeferredBinder.ScheduleBinding(prefab, scriptPath, info);
        Debug.Log($" 已更新脚本并记录延迟绑定任务：{prefab.name}");
    }

    private static string ReplaceRegion(string original, string regionName, string newContent)
    {
        string pattern = $@"(#region\s+{regionName})([\s\S]*?)(#endregion)";
        if (Regex.IsMatch(original, pattern))
        {
            Debug.Log("[PrefabScriptGenerator] 找到 AutoGenerated 区域，执行替换。");
            return Regex.Replace(original, pattern, $"$1\n{newContent}\n$3");
        }
        else
        {
            Debug.LogWarning("[PrefabScriptGenerator] 未找到 AutoGenerated 区域，附加到文件末尾。");
            return original + $"\n#region {regionName}\n{newContent}\n#endregion\n";
        }
    }

    private static string BuildFullClass(GameObject prefab, string author, string generatedCode, HashSet<string> usings)
    {
        var sb = new StringBuilder();
        foreach (var u in usings)
            sb.AppendLine($"using {u};");

        sb.AppendLine();
        sb.AppendLine($"// Auto Generated by {author} on {System.DateTime.Now:yyyy/MM/dd HH:mm}");
        sb.AppendLine($"public partial class {prefab.name} : KiraObject");
        sb.AppendLine("{");
        sb.AppendLine($"#region AutoGenerated");
        sb.AppendLine(generatedCode);
        sb.AppendLine($"#endregion");
        sb.AppendLine("\n\t// 在此区域外编写逻辑");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildGeneratedRegion(UIInfo info)
    {
        var sb = new StringBuilder();
        foreach (var e in info.entries)
            sb.AppendLine($"\t[SerializeField] private {e.typeName} {e.varName};");
        return sb.ToString();
    }

    private static string MergeUsings(string existingCode, HashSet<string> needed)
    {
        foreach (var u in needed)
        {
            if (!existingCode.Contains($"using {u};"))
            {
                existingCode = $"using {u};\n" + existingCode;
                Debug.Log($"[PrefabScriptGenerator] 添加缺失的 using：{u}");
            }
        }
        return existingCode;
    }

    private static UIInfo CollectUIInfo(GameObject prefab)
    {
        Debug.Log($"[PrefabScriptGenerator] 开始扫描 UI 组件：{prefab.name}");

        var info = new UIInfo();
        var usedNames = new HashSet<string>();

        // 改为递归扫描，以便控制层级遍历
        ScanRecursive(prefab.transform, prefab.transform, info, usedNames);

        info.usings.Add("UnityEngine");
        info.usings.Add("UnityEngine.UI");

        Debug.Log($"[PrefabScriptGenerator] 扫描完成，共 {info.entries.Count} 个绑定项。");
        return info;
    }

    private static void ScanRecursive(Transform root, Transform current, UIInfo info, HashSet<string> usedNames)
    {
        // 如果不是根节点，检查是否包含 KiraObject 组件
        if (current != root)
        {
            var comps = current.GetComponents<Component>();
            Component kiraComp = null;
            foreach (var c in comps)
            {
                if (c == null) continue;
                if (IsKiraObject(c.GetType()))
                {
                    kiraComp = c;
                    break;
                }
            }

            if (kiraComp != null)
            {
                // 发现子物体上有 KiraObject 组件，只引用该组件，不再深入扫描其子物体
                AddUIEntry(current, kiraComp, info, usedNames);
                Debug.Log($"[PrefabScriptGenerator] 识别到嵌套 KiraObject：{kiraComp.GetType().Name} <- {current.name}，停止向下扫描。");
                return;
            }
        }

        // 常规扫描：收集当前物体上的所有组件（排除 Transform）
        var allComps = current.GetComponents<Component>();
        foreach (var comp in allComps)
        {
            if (comp == null) continue;
            if (comp is Transform) continue;

            AddUIEntry(current, comp, info, usedNames);
        }

        // 递归遍历子物体
        foreach (Transform child in current)
        {
            ScanRecursive(root, child, info, usedNames);
        }
    }

    private static void AddUIEntry(Transform t, Component comp, UIInfo info, HashSet<string> usedNames)
    {
        var type = comp.GetType();
        string ns = type.Namespace;
        if (!string.IsNullOrEmpty(ns))
            info.usings.Add(ns);

        // 生成变量名：baseName_typeName（首字母小写），并确保全局唯一
        string baseName = ToVarName(t.name);
        string typeSuffix = type.Name;
        string suffixLower = char.ToLower(typeSuffix[0]) + typeSuffix.Substring(1);
        string candidate = baseName;
        if (!candidate.EndsWith(typeSuffix, System.StringComparison.OrdinalIgnoreCase))
            candidate = $"{candidate}_{suffixLower}";

        string unique = candidate;
        int idx = 1;
        while (usedNames.Contains(unique))
        {
            unique = $"{candidate}{idx}";
            idx++;
        }
        usedNames.Add(unique);

        info.entries.Add(new UIEntry
        {
            varName = unique,
            typeName = type.Name,
            target = comp
        });

        Debug.Log($"[PrefabScriptGenerator] 识别到组件：{type.Name} <- {t.name}");
    }

    private static bool IsKiraObject(System.Type type)
    {
        while (type != null && type != typeof(object))
        {
            if (type.Name == "KiraObject") return true;
            type = type.BaseType;
        }
        return false;
    }

    private static Component FindMainUIComponent(GameObject go)
    {
        System.Type[] priority = {
            typeof(UnityEngine.UI.Button),
            typeof(UnityEngine.UI.Toggle),
            typeof(UnityEngine.UI.Slider),
            typeof(UnityEngine.UI.InputField),      // Legacy InputField
            typeof(UnityEngine.UI.ScrollRect),
            typeof(UnityEngine.UI.Dropdown),
            typeof(UnityEngine.UI.Image),
            typeof(UnityEngine.UI.RawImage),
            typeof(UnityEngine.UI.Text),            // Legacy Text
            typeof(UnityEngine.UI.Scrollbar),
            typeof(UnityEngine.EventSystems.EventTrigger),
            typeof(UnityEngine.UI.Mask),
            typeof(UnityEngine.CanvasGroup),
            typeof(UnityEngine.UI.HorizontalLayoutGroup),
            typeof(UnityEngine.UI.VerticalLayoutGroup),
            typeof(UnityEngine.UI.GridLayoutGroup),
            typeof(UnityEngine.UI.ContentSizeFitter),
            typeof(UnityEngine.UI.LayoutElement),
            typeof(UnityEngine.UI.AspectRatioFitter)
        };

        foreach (var t in priority)
        {
            var c = go.GetComponent(t);
            if (c != null) return c;
        }

        var tmpType = System.Type.GetType("TMPro.TMP_Text, Unity.TextMeshPro");
        if (tmpType != null)
        {
            var tmpComp = go.GetComponent(tmpType);
            if (tmpComp != null) return tmpComp;
        }

        return go.transform;
    }

    private static string ToVarName(string objName)
    {
        var s = objName.Replace(" ", "_")
                       .Replace("-", "_")
                       .Replace("(", "_")
                       .Replace(")", "_");
        if (string.IsNullOrEmpty(s)) s = "unnamed";
        if (char.IsUpper(s[0])) s = char.ToLower(s[0]) + s.Substring(1);
        return s;
    }
}
#endregion


#region DeferredBinder
[InitializeOnLoad]
public static class DeferredBinder
{
    private const string PREF_KEY = "PrefabAutoBindInfo";

    static DeferredBinder()
    {
        AssemblyReloadEvents.afterAssemblyReload += OnScriptsReloaded;
    }

    public static void ScheduleBinding(GameObject prefab, string scriptPath, UIInfo info)
    {
        var data = new DeferredData
        {
            prefabPath = AssetDatabase.GetAssetPath(prefab),
            scriptPath = scriptPath,
            entries = info.entries
        };

        var json = JsonUtility.ToJson(data);
        EditorPrefs.SetString(PREF_KEY, json);
        Debug.Log($"[DeferredBinder] 已记录延迟绑定任务：{data.prefabPath}");
    }

    private static void OnScriptsReloaded()
    {
        if (!EditorPrefs.HasKey(PREF_KEY)) return;

        string json = EditorPrefs.GetString(PREF_KEY);
        EditorPrefs.DeleteKey(PREF_KEY);
        Debug.Log("[DeferredBinder] 检测到脚本重新加载，开始执行延迟绑定。");

        var data = JsonUtility.FromJson<DeferredData>(json);
        if (data == null)
        {
            Debug.LogWarning("[DeferredBinder] 反序列化延迟绑定数据失败。");
            return;
        }

        GameObject prefabAsset = AssetDatabase.LoadAssetAtPath<GameObject>(data.prefabPath);
        if (prefabAsset == null)
        {
            Debug.LogWarning($"[DeferredBinder] 找不到 Prefab：{data.prefabPath}");
            return;
        }

        string className = Path.GetFileNameWithoutExtension(data.scriptPath);
        System.Type scriptType = GetTypeByName(className);
        if (scriptType == null)
        {
            Debug.LogWarning($"[DeferredBinder] 找不到类型 {className}，绑定失败。");
            return;
        }

        Debug.Log($"[DeferredBinder] 成功找到脚本类型：{className}");
        GameObject prefabInstance = PrefabUtility.LoadPrefabContents(data.prefabPath);
        var comp = prefabInstance.GetComponent(scriptType);
        if (comp == null)
        {
            comp = prefabInstance.AddComponent(scriptType);
            Debug.Log($"[DeferredBinder] 在 Prefab 上添加脚本组件：{className}");
        }
        else
        {
            Debug.Log($"[DeferredBinder] Prefab 已存在脚本组件：{className}");
        }

        var so = new SerializedObject(comp);
        int bindCount = 0;
        foreach (var e in data.entries)
        {
            var prop = so.FindProperty(e.varName);
            if (prop != null)
            {
                prop.objectReferenceValue = e.target;
                bindCount++;
                Debug.Log($"[DeferredBinder] 绑定字段：{e.varName} ← {e.target}");
            }
        }
        so.ApplyModifiedProperties();

        PrefabUtility.SaveAsPrefabAsset(prefabInstance, data.prefabPath);
        PrefabUtility.UnloadPrefabContents(prefabInstance);

        Debug.Log($" 延迟绑定完成：{className} ({bindCount} 项)。");
    }

    private static System.Type GetTypeByName(string className)
    {
        foreach (var asm in System.AppDomain.CurrentDomain.GetAssemblies())
        {
            var type = asm.GetType(className);
            if (type != null)
                return type;
        }
        return null;
    }

    [System.Serializable]
    private class DeferredData
    {
        public string prefabPath;
        public string scriptPath;
        public List<UIEntry> entries;
    }
}
#endregion


#region DataTypes
[System.Serializable]
public class UIInfo
{
    public List<UIEntry> entries = new List<UIEntry>();
    public HashSet<string> usings = new HashSet<string>();
}

[System.Serializable]
public class UIEntry
{
    public string varName;
    public string typeName;
    public Object target;
}
#endregion
