using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Linq;

public static class StaticCodeGenerator
{
    private const string GENERATED_DIR = "Assets/Scripts/Generated/KiraStatics";
    private const string FILE_EXTENSION = ".cs";

    [MenuItem("Kira工具/调用链相关/生成所有映射代码")]
    public static void GenerateAllCodes()
    {
        var guids = AssetDatabase.FindAssets("t:MappingConfigSO");
        if (guids.Length == 0) return;

        bool anyGenerated = false;
        foreach (var guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            var config = AssetDatabase.LoadAssetAtPath<MappingConfigSO>(path);
            if (config != null)
            {
                GenerateCode(config);
                anyGenerated = true;
            }
        }
        
        if (anyGenerated)
        {
            AssetDatabase.Refresh();
            Debug.Log("所有静态映射代码生成成功！");
        }
    }

    private static void GenerateCode(MappingConfigSO config)
    {
        if (string.IsNullOrEmpty(config.RootClassName)) return;

        string rootClassName = SanitizeIdentifier(config.RootClassName);
        string outputFilePath = Path.Combine(GENERATED_DIR, rootClassName + FILE_EXTENSION);
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("// ----------------------------------------------------");
        sb.AppendLine($"// This file is GENERATED by {nameof(StaticCodeGenerator)}");
        sb.AppendLine("// DO NOT MODIFY MANUALLY");
        sb.AppendLine("// ----------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("namespace Game.Statics");
        sb.AppendLine("{");
        
        sb.AppendLine($"    public static class {rootClassName}");
        sb.AppendLine("    {");
        
        // 开始递归构建
        BuildStaticStructure(sb, config.Entries, 8);
        
        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteCodeFile(outputFilePath, sb.ToString());
    }
    
    private static void BuildStaticStructure(StringBuilder sb, List<MappingEntry> entries, int indentLevel)
    {
        var topLevelGroups = entries
            .Where(e => e.PathKeys.Count > 0)
            .GroupBy(e => e.PathKeys[0]);

        string indent = new string(' ', indentLevel);

        foreach (var group in topLevelGroups)
        {
            string key = SanitizeIdentifier(group.Key);
            var deeperEntries = group.Where(e => e.PathKeys.Count > 1).ToList();
            var finalEntry = group.FirstOrDefault(e => e.PathKeys.Count == 1);
            
            // ----------------------------------------------------------
            // 情况1：这是一个容器节点（下面还有子节点）
            // ----------------------------------------------------------
            if (deeperEntries.Any())
            {
                // 检查当前容器节点本身是否也是一个事件节点（Value为空）
                bool isContainerEvent = finalEntry != null && string.IsNullOrWhiteSpace(finalEntry.FinalValue);
                string inheritance = isContainerEvent ? " : IKiraEventKey" : "";

                sb.AppendLine();
                sb.AppendLine($"{indent}public class {key}{inheritance}");
                sb.AppendLine($"{indent}{{");
                
                // 如果容器节点本身有一个路径值（Value不为空），生成 Value 常量
                if (finalEntry != null && !string.IsNullOrWhiteSpace(finalEntry.FinalValue))
                {
                    string value = finalEntry.FinalValue.Replace("\"", "\\\"");
                    sb.AppendLine($"{indent}    public const string Value = \"{value}\";");
                }

                // 递归生成子节点
                List<MappingEntry> nextLevelEntries = deeperEntries
                    .Select(e => new MappingEntry 
                    { 
                        PathKeys = e.PathKeys.Skip(1).ToList(), 
                        FinalValue = e.FinalValue 
                    })
                    .ToList();
                    
                BuildStaticStructure(sb, nextLevelEntries, indentLevel + 4);
                
                sb.AppendLine($"{indent}}}");
            }
            // ----------------------------------------------------------
            // 情况2：这是一个叶子节点（没有子节点了）
            // ----------------------------------------------------------
            else if (finalEntry != null)
            {
                if (string.IsNullOrWhiteSpace(finalEntry.FinalValue))
                {
                    // Value为空 -> 生成事件类型 (Class)
                    sb.AppendLine($"{indent}public class {key} : IKiraEventKey {{ }}");
                }
                else
                {
                    // Value有值 -> 生成路径常量 (const string)
                    string value = finalEntry.FinalValue.Replace("\"", "\\\"");
                    sb.AppendLine($"{indent}public const string {key} = \"{value}\";");
                }
            }
        }
    }
    
    private static string SanitizeIdentifier(string input)
    {
        if (string.IsNullOrWhiteSpace(input)) return "InvalidIdentifier";
        string result = new string(input.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
        if (char.IsDigit(result.FirstOrDefault())) result = "_" + result;
        return result;
    }

    private static void WriteCodeFile(string path, string content)
    {
        string dirPath = Path.GetDirectoryName(path);
        if (!Directory.Exists(dirPath)) Directory.CreateDirectory(dirPath);
        // 简单检查内容是否变化，减少不必要的IO
        if (File.Exists(path) && File.ReadAllText(path, Encoding.UTF8) == content) return; 
        File.WriteAllText(path, content, Encoding.UTF8);
    }
}