using UnityEditor;
using UnityEngine;
using System.Text;
using System.IO;
using System.Linq; // 用于 Path.GetFileNameWithoutExtension

public static class ViewModelGenerator
{
    // 模板使用占位符：{0} = 时间, {1} = ViewModel名称, {2} = 属性代码块
    private const string ViewModelTemplate = 
@"//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由 MVVM Editor Toolchain 自动生成。
//     生成时间: {0}
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
// TODO: 根据您的 Model 命名空间，可能需要添加额外的 using 语句
// using YourProject.Models; 

// 假设您有一个基类 ViewModelBase 来处理属性变更通知
public class {1} : ViewModelBase 
{{
{2}
    // 构造函数或其他初始化逻辑...
    public {1}()
    {{
        // TODO: 注册 Model 监听、初始化属性等
    }}
}}";

    [MenuItem("Assets/Kira工具/MVVM/为VMSO生成ViewModel脚本", true)]
    public static bool CanGenerateViewModel()
    {
        // 只有选中了 ViewModelConfigSO 实例时才启用菜单
        return Selection.activeObject is ViewModelConfigSO;
    }

    [MenuItem("Assets/Kira工具/MVVM/为VMSO生成ViewModel脚本")]
    public static void GenerateViewModel()
    {
        var config = Selection.activeObject as ViewModelConfigSO;
        if (config == null) return;

        string viewModelName = config.ViewModelName;
        if (string.IsNullOrEmpty(viewModelName) || !System.CodeDom.Compiler.CodeGenerator.IsValidLanguageIndependentIdentifier(viewModelName))
        {
            Debug.LogError($"ViewModel 名称 '{viewModelName}' 无效或为空。请在 SO 中设置一个有效的类名。");
            return;
        }

        StringBuilder propertyBuilder = new StringBuilder();
        
        // 遍历所有绑定配置，生成 C# 属性
        foreach (var binding in config.Bindings)
        {
            string modelFullName = binding.modelTypeName;
            string fieldName = binding.fieldName;

            // 检查配置是否完整
            if (string.IsNullOrEmpty(modelFullName) || string.IsNullOrEmpty(fieldName))
            {
                Debug.LogWarning($"Skipping incomplete binding in {config.name}. Model: '{modelFullName}', Field: '{fieldName}'");
                continue;
            }
            
            // 1. 获取 Model 字段的实际 C# 类型名称
            string fieldType = MVVMDataCache.GetFieldType(modelFullName, fieldName);
            
            // 2. 构造属性名称 (例如：HPModel_CurrentHP)
            // 提取 Model 的短名称作为前缀，确保名称的唯一性
            // 移除命名空间，只保留类名
            string modelShortName = modelFullName.Contains('.') 
                                    ? modelFullName.Substring(modelFullName.LastIndexOf('.') + 1)
                                    : modelFullName;

            string propertyName = $"{modelShortName}_{fieldName}"; 

            // 属性代码块生成
            propertyBuilder.AppendLine($"    // Bound to: {modelFullName}.{fieldName}");
            propertyBuilder.AppendLine($"    private {fieldType} _{propertyName};");
            propertyBuilder.AppendLine($"    public {fieldType} {propertyName}"); 
            propertyBuilder.AppendLine("    {");
            propertyBuilder.AppendLine($"        get => _{propertyName};");
            propertyBuilder.AppendLine("        set => SetProperty(ref _" + propertyName + ", value);");
            propertyBuilder.AppendLine("    }");
            propertyBuilder.AppendLine("");
        }
        
        // 格式化最终代码
        string finalCode = string.Format(
            ViewModelTemplate,
            System.DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
            viewModelName,
            propertyBuilder.ToString()
        );

        // 确定生成路径
        string path = AssetDatabase.GetAssetPath(config);
        string directory = Path.GetDirectoryName(path);
        string fullPath = Path.Combine(directory, $"{viewModelName}.cs");

        // 写入文件
        File.WriteAllText(fullPath, finalCode, Encoding.UTF8);
        
        // 刷新 Unity
        AssetDatabase.Refresh();
        Debug.Log($"Successfully generated ViewModel: {viewModelName} at {fullPath}");
    }
}