//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由 MVVM Editor Toolchain 自动生成。
//     生成时间: 2025-11-01 22:11:34
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
// TODO: 根据您的 Model 命名空间，可能需要添加额外的 using 语句
// using YourProject.Models; 

// 假设您有一个基类 ViewModelBase 来处理属性变更通知
public class TestHPViewModel : ViewModelBase 
{
    // Bound to: TestHPModel.CurrentHP
    private int _TestHPModel_CurrentHP;
    public int TestHPModel_CurrentHP
    {
        get => _TestHPModel_CurrentHP;
        set => SetProperty(ref _TestHPModel_CurrentHP, value);
    }

    // Bound to: TestHPModel.MaxHP
    private int _TestHPModel_MaxHP;
    public int TestHPModel_MaxHP
    {
        get => _TestHPModel_MaxHP;
        set => SetProperty(ref _TestHPModel_MaxHP, value);
    }


    // 构造函数或其他初始化逻辑...
    public TestHPViewModel()
    {
        // TODO: 注册 Model 监听、初始化属性等
    }
}